### ISSUE TITLE
RAM issue and Matlab

### ISSUE THREAD

**Issue by gmbcrazy** [magland/mountainlab#186]
Hi, I have mainly two questions.

1.  My PC's memory (64G) is not enough to re-write data in matlab to .mda format (writemda.m) in windows. My data is 32 channels 20kHz recording and 1 hours long. In future we will have even more channels and longer recording.      
    Will it improve in linux system to do so? If I have to purchase a workstation to process the data, what kind of setup (memory, CPU) do you suggest?

2.  I tried simple_sort.m in matlab with my own data, it works well.  I also noticed that there's a alg_scda_005.m file, but recently I can't run it successfully.    Which one do you suggest to use if I prefer to sort in matlab enviroment?

simple_sort.m is just controlled by matlab while in alg_scda_005.m, there're more details. Am I right?

Thank you so much again.

LU

**Comment by magland** [comment]
1. Yes, I would recommend acquiring a linux system to do the processing. It's hard to suggest specs, because it depends on the size of your datasets. For 32 channels and 1 hour, you should be able to get away with relatively small amount of RAM (32 GB). But if you plan on using more channel, go for more. The number of CPU cores will affect the speed of processing. I highly recommend SSD drives.

2. Those .m files are old development codes. I would highly recommend using the command-line tools for sorting.
